# Generated by Django 4.2.7 on 2025-11-15 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_unit", models.CharField(blank=True, max_length=20)),
                ("data_points", models.JSONField(default=list)),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("INCREASING", "Increasing"),
                            ("DECREASING", "Decreasing"),
                            ("STABLE", "Stable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trend_strength", models.FloatField(default=0.0)),
                ("current_value", models.FloatField(blank=True, null=True)),
                ("average_value", models.FloatField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("change_percentage", models.FloatField(blank=True, null=True)),
                ("normal_range_min", models.FloatField(blank=True, null=True)),
                ("normal_range_max", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_trends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_trends",
                "indexes": [
                    models.Index(
                        fields=["patient", "metric_name"],
                        name="health_tren_patient_383fba_idx",
                    )
                ],
                "unique_together": {("patient", "metric_name")},
            },
        ),
        migrations.CreateModel(
            name="HealthRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DIABETES", "Diabetes"),
                            ("HYPERTENSION", "Hypertension"),
                            ("HEART_DISEASE", "Heart Disease"),
                            ("KIDNEY_DISEASE", "Kidney Disease"),
                            ("LIVER_DISEASE", "Liver Disease"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(default=0.0, help_text="Risk score (0-100)"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MODERATE", "Moderate Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("contributing_factors", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_records",
                    models.ManyToManyField(
                        blank=True,
                        related_name="risk_assessments",
                        to="core.healthrecord",
                    ),
                ),
            ],
            options={
                "db_table": "health_risks",
                "ordering": ["-risk_score", "-assessed_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-risk_score"],
                        name="health_risk_patient_2cd49a_idx",
                    ),
                    models.Index(
                        fields=["category", "risk_level"],
                        name="health_risk_categor_ae0d9a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TREND", "Trend Analysis"),
                            ("RISK", "Risk Assessment"),
                            ("ANOMALY", "Anomaly Detection"),
                            ("PREDICTION", "Health Prediction"),
                            ("RECOMMENDATION", "Recommendation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("predictions", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, help_text="Confidence score (0-1)"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_records",
                    models.ManyToManyField(
                        blank=True, related_name="insights", to="core.healthrecord"
                    ),
                ),
            ],
            options={
                "db_table": "health_insights",
                "ordering": ["-created_at", "-severity"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="health_insi_patient_457ffa_idx",
                    ),
                    models.Index(
                        fields=["type", "severity"], name="health_insi_type_928f48_idx"
                    ),
                ],
            },
        ),
    ]
