"""
AI/ML models for health insights and predictive analytics.
"""
from django.db import models
from django.contrib.auth import get_user_model
from core.models import HealthRecord

User = get_user_model()


class HealthInsight(models.Model):
    """Health insights generated by AI analysis."""
    
    class InsightType(models.TextChoices):
        TREND = 'TREND', 'Trend Analysis'
        RISK = 'RISK', 'Risk Assessment'
        ANOMALY = 'ANOMALY', 'Anomaly Detection'
        PREDICTION = 'PREDICTION', 'Health Prediction'
        RECOMMENDATION = 'RECOMMENDATION', 'Recommendation'
    
    class Severity(models.TextChoices):
        LOW = 'LOW', 'Low'
        MEDIUM = 'MEDIUM', 'Medium'
        HIGH = 'HIGH', 'High'
        CRITICAL = 'CRITICAL', 'Critical'
    
    # Ownership
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='health_insights')
    
    # Insight Info
    type = models.CharField(max_length=20, choices=InsightType.choices)
    title = models.CharField(max_length=255)
    description = models.TextField()
    severity = models.CharField(max_length=20, choices=Severity.choices, default=Severity.LOW)
    
    # Related Records
    related_records = models.ManyToManyField(HealthRecord, related_name='insights', blank=True)
    
    # Data
    metrics = models.JSONField(default=dict, blank=True)  # Key metrics analyzed
    predictions = models.JSONField(default=dict, blank=True)  # Future predictions
    recommendations = models.JSONField(default=list, blank=True)  # AI recommendations
    
    # Metadata
    confidence_score = models.FloatField(default=0.0, help_text="Confidence score (0-1)")
    is_active = models.BooleanField(default=True)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'health_insights'
        ordering = ['-created_at', '-severity']
        indexes = [
            models.Index(fields=['patient', '-created_at']),
            models.Index(fields=['type', 'severity']),
        ]
    
    def __str__(self):
        return f"{self.title} - {self.patient.get_full_name()}"


class HealthTrend(models.Model):
    """Health trends and patterns."""
    
    # Ownership
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='health_trends')
    
    # Trend Info
    metric_name = models.CharField(max_length=100)  # e.g., 'HbA1c', 'Blood Pressure', 'Weight'
    metric_unit = models.CharField(max_length=20, blank=True)  # e.g., 'mg/dL', 'mmHg'
    
    # Trend Data
    data_points = models.JSONField(default=list)  # List of {date, value, record_id}
    trend_direction = models.CharField(
        max_length=20,
        choices=[('INCREASING', 'Increasing'), ('DECREASING', 'Decreasing'), ('STABLE', 'Stable')]
    )
    trend_strength = models.FloatField(default=0.0)  # -1 to 1
    
    # Statistics
    current_value = models.FloatField(null=True, blank=True)
    average_value = models.FloatField(null=True, blank=True)
    min_value = models.FloatField(null=True, blank=True)
    max_value = models.FloatField(null=True, blank=True)
    change_percentage = models.FloatField(null=True, blank=True)  # Percentage change
    
    # Normal Range
    normal_range_min = models.FloatField(null=True, blank=True)
    normal_range_max = models.FloatField(null=True, blank=True)
    
    # Timestamps
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'health_trends'
        unique_together = ['patient', 'metric_name']
        indexes = [
            models.Index(fields=['patient', 'metric_name']),
        ]
    
    def __str__(self):
        return f"{self.metric_name} Trend - {self.patient.get_full_name()}"


class HealthRisk(models.Model):
    """Health risk assessments."""
    
    class RiskCategory(models.TextChoices):
        DIABETES = 'DIABETES', 'Diabetes'
        HYPERTENSION = 'HYPERTENSION', 'Hypertension'
        HEART_DISEASE = 'HEART_DISEASE', 'Heart Disease'
        KIDNEY_DISEASE = 'KIDNEY_DISEASE', 'Kidney Disease'
        LIVER_DISEASE = 'LIVER_DISEASE', 'Liver Disease'
        OTHER = 'OTHER', 'Other'
    
    # Ownership
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='health_risks')
    
    # Risk Info
    category = models.CharField(max_length=20, choices=RiskCategory.choices)
    risk_score = models.FloatField(default=0.0, help_text="Risk score (0-100)")
    risk_level = models.CharField(
        max_length=20,
        choices=[
            ('LOW', 'Low Risk'),
            ('MODERATE', 'Moderate Risk'),
            ('HIGH', 'High Risk'),
            ('CRITICAL', 'Critical Risk')
        ]
    )
    
    # Details
    description = models.TextField()
    contributing_factors = models.JSONField(default=list)  # List of factors contributing to risk
    recommendations = models.JSONField(default=list)  # Recommendations to reduce risk
    
    # Related Records
    related_records = models.ManyToManyField(HealthRecord, related_name='risk_assessments', blank=True)
    
    # Timestamps
    assessed_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'health_risks'
        ordering = ['-risk_score', '-assessed_at']
        indexes = [
            models.Index(fields=['patient', '-risk_score']),
            models.Index(fields=['category', 'risk_level']),
        ]
    
    def __str__(self):
        return f"{self.category} Risk - {self.patient.get_full_name()} ({self.risk_level})"

